# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:

  - package-ecosystem: "pip"
    directory: ".\\Frontend\\requirements.txt"
    schedule:
      interval: daily
    labels:
      - "python"
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 99
    labels:
      - "gitActions"
      - "dependencies"
