version: "3.3"

services:
  frontend:
    tty: true
    container_name: eco_monitor
    hostname: eco_monitor
    ports:
      - 3000:3000
      - 2999:2999
    build:
      context: Frontend
      dockerfile: Dockerfile
    restart: always

    volumes:
      - ./Frontend:/app
    networks:
      - external
      - internal
      - web
    environment:
      DB_HOST: eco_monitor_mysql
      DB_USER: root
      DB_PASSWORD: passwordsicura
      DB_NAME: edciv


  

  mysql:
    hostname: eco_monitor_mysql
    container_name: eco_monitor_mysql
    ports:
      - 3306:3306

    build:
      context: Database
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: passwordsicura
      MYSQL_DATABASE: edciv
      PORT: 3306
    volumes:
      - ./Database:/appdb
    networks:
      - web
      - internal
    


networks:
  web:
    driver: bridge
  internal:
    driver: bridge
    internal: true
  external:
    driver: bridge
